#!/bin/sh

DEBUG=0

while [ $# -ge 1 ]
do
case $1 in
--sourcedir)
	shift
	SOURCEDIR=$1
	shift
;;
--ltag)
	shift
	TAG=$1
	shift
;;
-d)
	shift
	DEBUG=1
;;
*)
	echo "ERROR: unknow argument $1"
	exit 1
;;
esac
done

if [ ! -e "$SOURCEDIR" ];then
	echo "ERROR: $SOURCEDIR does not exists"
	exit 1
fi

cd $SOURCEDIR || exit $?

git fetch || exit $?

TAG_TO_CHECK=$(git tag | grep -v rc | grep $TAG | tail -n1)
if [ -z "$TAG_TO_CHECK" ];then
	exit 1
fi
git checkout $TAG_TO_CHECK
exit $?
